# Generated by Django 3.1.3 on 2020-11-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('species', models.CharField(max_length=20)),
                ('generation', models.IntegerField()),
                ('colour', models.CharField(choices=[('GO', 'Gold'), ('SI', 'Silver'), ('BL', 'Blue'), ('RE', 'Red')], max_length=2)),
                ('growth_rate', models.CharField(choices=[('FA', 'Fast'), ('ME', 'Medium'), ('SL', 'Slow')], max_length=2)),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('type', models.CharField(choices=[('GR', 'Grass'), ('PO', 'Poison'), ('FL', 'Flying'), ('FI', 'Fire')], max_length=2)),
                ('image', models.CharField(max_length=150)),
            ],
        ),
    ]
